[2020-06-29 11:31:48,625] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_stats.extract 2020-06-27T00:03:00+00:00 [queued]>
[2020-06-29 11:31:48,637] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_stats.extract 2020-06-27T00:03:00+00:00 [queued]>
[2020-06-29 11:31:48,637] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-29 11:31:48,637] {taskinstance.py:880} INFO - Starting attempt 5 of 6
[2020-06-29 11:31:48,637] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-29 11:31:48,644] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): extract> on 2020-06-27T00:03:00+00:00
[2020-06-29 11:31:48,646] {standard_task_runner.py:53} INFO - Started process 9304 to run task
[2020-06-29 11:31:48,681] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: covid_stats.extract 2020-06-27T00:03:00+00:00 [running]> nineleaps-ThinkPad-E480
[2020-06-29 11:31:48,959] {taskinstance.py:1145} ERROR - global name 'valid_data' is not defined
Traceback (most recent call last):
  File "/home/nineleaps/.local/lib/python2.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/nineleaps/.local/lib/python2.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/nineleaps/.local/lib/python2.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nineleaps/airflow/plugins/extract.py", line 27, in extract
    pandas_df = pd.DataFrame(valid_data)
NameError: global name 'valid_data' is not defined
[2020-06-29 11:31:48,960] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-06-29 11:31:58,624] {logging_mixin.py:112} INFO - [2020-06-29 11:31:58,623] {local_task_job.py:103} INFO - Task exited with return code 1
